// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeChat.WebApi.ORM.Models
{
    public partial class TbApiLog
    {
        public int Index { get; set; }
        public string Region { get; set; }
        public string Action { get; set; }
        public string Arguments { get; set; }
        public string Ip { get; set; }
        public string Address { get; set; }
        public string Guid { get; set; }
        public DateTime LogTime { get; set; }
    }
}