// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeChat.WebApi.ORM.Models
{
    public partial class TbChatLog
    {
        public string Guid { get; set; }
        public string Sender { get; set; }
        public string Receiever { get; set; }
        public string Action { get; set; }
        public string Body { get; set; }
        public DateTime SendTime { get; set; }
    }
}