// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeChat.WebApi.ORM.Models
{
    public partial class TbUser
    {
        public string Quid { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Sign { get; set; }
    }
}